<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PreviewFile.Domain\PreviewFile.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Translator\en\pdf.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>pdf.resx</DependentUpon>
    </Compile>
    <Compile Update="Translator\vi\pdf.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>pdf.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Translator\en\pdf.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>pdf.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Translator\vi\pdf.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>pdf.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
